server:
  port: 8080
spring:
  #cache设置
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    #应用的名称，可选
    name: reggie_take_out
  shardingsphere:
    datasource:
      names:
        master,slave
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.59.24:3306/reggie?serverTimezone=Asia/Shanghai&user=root&password=910630&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 2788
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.59.23:3306/reggie?serverTimezone=Asia/Shanghai&user=root&password=910630&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 2788
    masterslave:
        # 读写分离配置
        load-balance-algorithm-type: round_robin #轮询
        # 最终的数据源名称
        name: dataSource
        # 主库数据源名称
        master-data-source-name: master
        # 从库数据源名称列表，多个逗号分隔
        slave-data-source-names: slave
    props:
        sql:
          show: true #开启SQL显示，默认false


  servlet:
    #文件大小 MB必须大写
    #  maxFileSize 是单个文件大小
    #  maxRequestSize是设置总上传的数据大小
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    host: 127.0.0.1
    port: 6379
    #password: root@2788
    database: 1

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true

    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: isDeleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

reggie:
    path: E:\software\img\


